.github/workflows/buildx-releases-json.yml
Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>
=> ci: enable open-pr job

.github/workflows/buildx-releases-json.yml
Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>
=> ci: fix releases-json workflow

__tests__/buildx/install.test.ts, src/buildx/install.ts
Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>
=> buildx: use correct url for getRelease

__tests__/buildkit/buildkit.test.ts, __tests__/buildx/builder.test.ts, src/buildkit/buildkit.ts, src/buildx/builder.ts, src/types/builder.ts
related to https://github.com/docker/setup-buildx-action/pull/204/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R146-R159
=> builder: fix breaking change on node fields

__tests__/docker/install.test.e2e.ts, __tests__/docker/install.test.ts, src/docker/install.ts
=> docker: support latest on install

.github/workflows/buildx-releases-json.yml, .github/workflows/docker-releases-json.yml
full diff: https://github.com/crazy-max/.github/compare/2a596c917a8ad3e6203ae99b777148525a2e00d5...6dc31870ca6c4f8489bf5a408ab38fae60f47eec
=> Bump releases-json action to 6dc3187

src/buildx/install.ts
=> buildx: set consistent platform when caching binary

src/buildx/bake.ts
related to https://github.com/docker/bake-action/actions/runs/4533586655/jobs/7986601676?pr=104#step:6:109
=> bake: check for empty source

.github/workflows/virtual-env.yml
follow-up https://github.com/actions/runner-images/pull/7388
=> ci: fix virtual env workflow

src/git.ts
=> git: fall back to git tag in detached HEAD state

__tests__/docker/install.test.itg.ts, src/docker/install.ts
related to https://github.com/crazy-max/ghaction-setup-docker/actions/runs/5899768109/job/16002819956#step:4:17
5 retries don't look to be enough in some cases. Increasing to 10 should be enough.
=> docker(install): increase number of retries

.github/workflows/buildx-lab-releases-json.yml
cc @sgarcez 
See https://github.com/docker/actions-toolkit/actions/runs/5983293458/job/16233283259?pr=150#step:3:5
=> ci: generate buildx-lab-releases.json

__tests__/docker/install.test.itg.ts, src/docker/assets.ts, src/docker/install.ts
follow-up https://github.com/crazy-max/ghaction-setup-docker/issues/18#issuecomment-1694777875
closes #158
=> docker(install): allow passing colima start args

dev.Dockerfile
* docker 24.0.5
* buildx 0.11.2
=> dev: update docker and buildx to latest

src/docker/install.ts
=> docker(install): fix download for arm64 arch

src/context.ts
carry and closes #194 with changes discussed.
=> Use RUNNER_TEMP as temp directory

__tests__/git.test.ts, src/git.ts
Should fix https://github.com/docker/metadata-action/issues/362#issuecomment-1851504976
=> fix(git): supports grafted pull refs

__tests__/util.test.ts, src/buildx/install.ts, src/cache.ts, src/util.ts
carries some changes from https://github.com/docker/actions-toolkit/pull/200
=> cache class for tool caching with gha

__tests__/util.test.ts
related to https://github.com/docker/build-push-action/issues/1072
=> test: keep quotes around fields

.github/workflows/test.yml
=> ci(test): pin to macos-13 for docker install

__tests__/buildx/bake.test.ts, __tests__/buildx/build.test.ts, src/buildx/bake.ts, src/buildx/build.ts, src/types/bake.ts, src/types/build.ts
Will be used for GHA summary to retrieve refs from metadata file.
=> buildx: metadata and refs resolution for build and bake

.github/dependabot.yml
related to https://github.com/docker/actions-toolkit/pull/335#issuecomment-2109669235
=> chore: ignore azure/storage-blob updates

src/types/intoto/intoto.ts, src/types/intoto/slsa_provenance/v0.2/provenance.ts
related to https://github.com/docker/actions-toolkit/pull/347
=> intoto and provenance types

__tests__/buildx/build.test.ts, __tests__/fixtures/metadata.json, src/buildx/build.ts, src/types/buildx/build.ts
follow-up https://github.com/docker/buildx/pull/2280
=> buildx(build): resolveProvenance from metadata

__tests__/github.test.ts, src/github.ts
Avoid using internals from peer dependencies in our actions like https://github.com/docker/build-push-action/pull/1160/files#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR4
=> github: isGHES func

__tests__/docker/docker.test.ts, src/buildkit/buildkit.ts, src/buildx/history.ts, src/docker/docker.ts, src/docker/install.ts
relates to https://github.com/docker/build-push-action/issues/1177
=> disable DCT for docker commands

src/docker/install.ts
relates to #412 
Just for completeness but should not have any impact.
=> missing DCT removal for a docker command

.github/actions/macos-setup-qemu/action.yml, .github/workflows/test.yml
=> ci(test): enforce QEMU 9.0.2

__tests__/undock/install.test.itg.ts, __tests__/undock/install.test.ts, src/types/undock/undock.ts, src/undock/install.ts
follow-up https://github.com/docker/actions-toolkit/pull/438#pullrequestreview-2397522924
@vvoland I will look at using this as follow-up for docker install.
=> undock install

.github/workflows/validate.yml, dev.Dockerfile, docker-bake.hcl
follow-up https://github.com/docker/actions-toolkit/pull/476#issuecomment-2445893950
=> dockerfile validation

__tests__/docker/install.test.itg.ts, src/docker/assets.ts
follow-up https://github.com/lima-vm/lima/pull/2848
=> docker(install): update lima images to ubuntu 24.04

src/types/buildx/bake.ts
follow-up:
* https://github.com/docker/buildx/pull/2556
* https://github.com/docker/buildx/pull/2666
=> bake: missing attributes on group and target types

__tests__/util.test.ts, src/util.ts
follow-up https://github.com/docker/setup-docker-action/pull/138#discussion_r1882442730
=> util: getInputNumber func

__tests__/.fixtures/bake-03-default.json, __tests__/.fixtures/bake-03.hcl, src/buildx/bake.ts, src/types/buildx/bake.ts
follow-up https://github.com/docker/actions-toolkit/pull/514#issuecomment-2577695801
=> bake: composable attributes for attestations support

__tests__/.fixtures/bake-03-default.json, __tests__/.fixtures/bake-03.hcl, __tests__/buildx/bake.test.ts, src/buildx/bake.ts
Similar to what we have with build: https://github.com/docker/actions-toolkit/blob/e36200f7541caa6b67c992e2a592e4d885f12669/src/buildx/build.ts#L304-L311
=> bake: hasGitAuthTokenSecret func

hack/dockerfiles/license.Dockerfile
similar to https://github.com/docker/cli-docs-tool/pull/64
=> dockerfile: use go install for addlicense and update to v1.1.1

__tests__/buildx/install.test.ts, __tests__/compose/install.test.ts, src/compose/install.ts, src/types/compose/compose.ts
similar to https://github.com/docker/actions-toolkit/pull/155
=> compose: cloud releases support

src/buildx/build.ts
In `docker/build-push-action` a build secret can be passed directly in the workflow using key/value pair with the `secrets` input:
```yaml
-
name: Build and push
uses: docker/build-push-action@v6
with:
push: true
tags: user/app:latest
secrets: |
GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}
```
Registered GitHub Secrets within the repository are already redacted in the logs but some users might pass them as plain text like:
```yaml
-
name: Build and push
uses: docker/build-push-action@v6
with:
push: true
tags: user/app:latest
secrets: |
MYSECRET=foo
```
Even if this value is already leaked within the workflow we can at least always register as secret the value passed as build secret string here.
=> buildx(build): always register as secret the value passed as build secret string

.github/workflows/validate.yml, .github/workflows/virtual-env.yml
https://github.com/actions/runner-images/issues/11101
=> ci: update ubuntu runners to latest

.github/workflows/test.yml
=> ci: skip image source on windows runner for docker install
