- src/types/builder.ts
For builder creation when appending additional nodes in `setup-buildx-action`.
> builder: add Node type

- __tests__/buildx/install.test.ts
- src/buildx/install.ts
Split install from download and build methods so we can have clear grouped output in `setup-buildx-action`.
> buildx: split install from download and build methods

- __tests__/docker.test.ts
- src/docker.ts
Related to https://github.com/docker/setup-buildx-action/actions/runs/4270612172/jobs/7434517458#step:4:13
Looks like `docker context show` is only available since Docker 23: https://github.com/docker/cli/pull/3567.
What's odd is the command exists on Docker Desktop with Docker CLI 20.10.22 ??
```
$ docker --version
Docker version 20.10.22, build 3a2c30b
$ docker context --help
Manage contexts
Usage:
docker context [command]
Available Commands:
create      Create new context
export      Export a context to a tar or kubeconfig file
import      Import a context from a tar or zip file
inspect     Display detailed information on one or more contexts
list        List available contexts
rm          Remove one or more contexts
show        Print the current context
update      Update a context …
```
> docker: fix context command

- __tests__/git.test.ts
- src/buildx/install.ts
- src/git.ts
- src/types/git.ts
follow-up https://github.com/docker/metadata-action/pull/248
Adds alternative context to the GitHub one for Git.
@neilime PTAL. I keep you posted when we cut a new release of the actions-toolkit so you can rebase your PR on the metadata-action repo. You could then have smth like:
```diff
---
src/context.ts | 24 +++++++++++++++++++++++-
1 file changed, 23 insertions(+), 1 deletion(-)
diff --git a/src/context.ts b/src/context.ts
index 3738b23..dd819c9 100644
--- a/src/context.ts
+++ b/src/context.ts
@@ -1,7 +1,11 @@
import * as core from '@actions/core';
+import {Context} from '@actions/github/lib/context';
+import {Git} from '@docker/actions-toolkit/lib/git';
+import {GitHub} from '@docker/actions-toolkit/lib/github';
import {Util} from '@docker/actions-toolkit/lib/util';
export interface …
```
> git: alternative github context and additional methods

- .github/workflows/build.yml
- .github/workflows/docker-releases-json.yml
- .github/workflows/e2e.yml
- .github/workflows/test.yml
Will be used to check for latest stable like we do with buildx.
> ci: generate docker-releases.json

- __tests__/buildx/builder.test.ts
- __tests__/fixtures/inspect7.txt
- src/buildx/builder.ts
Encounter this issue while working on https://github.com/docker/setup-buildx-action/pull/219
See https://github.com/docker/setup-buildx-action/actions/runs/4392990659/jobs/7693097407#step:4:179
> builder: fix regex to parse driver-opts

- package.json
- yarn.lock
Looks like dependabot didn't update the `package.json` in https://github.com/docker/actions-toolkit/pull/65/files
> build(deps): bump csv-parse from 5.3.5 to 5.3.6

- src/buildx/bake.ts
The bake action has support for setting a custom working directory. We need this for parsing definitions in our toolkit too.
> bake: workdir support for parsing definitions

- __tests__/docker/docker.test.ts
- __tests__/fixtures/docker-config-auths.json
- __tests__/fixtures/docker-config-proxies.json
- src/docker/docker.ts
- src/types/docker.ts
related to https://github.com/docker/build-push-action/pull/872
We need a way to inform users that proxy configuration from docker config might be used and could potentially affect their builds in workflows. Could have been done using the buildx inspect command in https://github.com/docker/buildx/pull/1864 but this is not really suitable.
> docker: configFile method

- __tests__/util.test.ts
- src/util.ts
related to https://github.com/docker/bake-action/issues/136
> util: comment opt for getInputList

- __tests__/buildx/builder.test.ts
- __tests__/fixtures/inspect10.txt
- __tests__/fixtures/inspect8.txt
- __tests__/fixtures/inspect9.txt
- src/buildx/builder.ts
- src/types/builder.ts
Not proud of this but while waiting for JSON format support for the `inspect` command, let's continue to "support" the raw output in the meantime.
> buildx: handle new fields when parsing inspect output

- __tests__/buildx/install.test.ts
- __tests__/util.test.ts
- package.json
- src/buildx/install.ts
- src/util.ts
- yarn.lock
When installing buildx, downloaded binary is not cached. As public GitHub runners are ephemeral, this can take some time to download the binary for each workflow execution: https://github.com/docker/setup-buildx-action/actions/runs/5462992694/jobs/9943119048#step:3:1
And even more if building from source: https://github.com/docker/setup-buildx-action/actions/runs/5462992694/jobs/9943110665#step:3:1
With these changes, binary will be cached to the [hosted tool cache](https://github.com/actions/toolkit/tree/main/packages/tool-cache) like the official actions do today with node, go, ...
This is fine for self-hosted runners but not public runners as hosted tool cache is pruned when a job is completed. To solve this issue, we also cache the binary to the GitHub Actions Cache backend.
> buildx: cache binary to hosted tool cache and GHA cache backend

- src/buildx/install.ts
When building buildx on macOS runner when Docker engine is installed it will build against `linux/amd64` instead of `darwin/amd64`. We should always match the local platform.
cc @maxcleme
> buildx: build for local platform

- __tests__/docker/install.test.itg.ts
- src/docker/assets.ts
- src/docker/install.ts
follow-up https://github.com/docker/actions-toolkit/pull/150#issuecomment-1694196417
Adds `SIGN_QEMU_BINARY` env as workaround to replace existing signature with required entitlements per https://github.com/abiosoft/colima/issues/786#issuecomment-1693629650. Also adds extra commit to display debug logs on failure.
> docker(install): SIGN_QEMU_BINARY env as workaround to replace existing signature

- src/docker/assets.ts
- src/docker/install.ts
- src/util.ts
related to: https://github.com/crazy-max/ghaction-setup-docker/actions/runs/5984159898/job/16235064091#step:13:27
```
Cleaning up runDir
/usr/bin/sudo rm -rf /home/runner/setup-docker-action-b2d1aae1-6bc5-48e6-b3d2-3f6b0ff55a03
rm: cannot remove '/home/runner/setup-docker-action-b2d1aae1-6bc5-48e6-b3d2-3f6b0ff55a03/execroot/netns/73797e176e19': Device or resource busy
rm: cannot remove '/home/runner/setup-docker-action-b2d1aae1-6bc5-48e6-b3d2-3f6b0ff55a03/data/overlay2/dd999632be8bbc1d1b90e1c22d3ad56c9ede1ff04b50b54af1877f0617de17d7/merged': Device or resource busy
```
> docker(install): stop docker daemon gracefully on linux

- __tests__/buildx/install.test.ts
- src/buildx/install.ts
- src/types/buildx.ts
follow-up https://github.com/docker/actions-toolkit/pull/150
cc @sgarcez
> buildx: alternative release repos to download buildx

- dev.Dockerfile
- package.json
- yarn.lock
follow-up https://github.com/docker/login-action/pull/590#discussion_r1315431040
Node 16 reaches the [end of life on 11 Sep 2023](https://nodejs.org/en/blog/announcements/nodejs16-eol). Node 20 is supported on GitHub Runners since https://github.com/actions/runner/releases/tag/v2.308.0.
> dev: update to node 20

- __tests__/git.test.ts
- src/git.ts
Properly manage detached HEAD when getting ref.
- Check if we are in a detached HEAD context
- If so handle detached tag and branch context
> fix(git): handle properly detached HEAD ref

- __tests__/buildx/inputs.test.ts
- src/buildx/inputs.ts
When trying to implement an input for secrets defined by environment variables to the [build-push-action](https://github.com/elias-lundgren/docker-build-push-action) I made use of the new `resolveBuildSecretEnv` implemented in: https://github.com/docker/actions-toolkit/commit/a1ffbe96065f5934066c01459a17967107273cc6.
I implemented [a test](https://github.com/elias-lundgren/docker-build-push-action/blob/70138029d25c33c53e7050d2f0fc8279ea5574d9/.github/workflows/ci.yml#L396-L419) for the new input and it didn't work due to csv parsing breaking because of the quotes around the env variable name as can be seen [here](https://github.com/elias-lundgren/docker-build-push-action/actions/runs/6314626381). After monkeypatching this function (removing the `"` around the env variable name) and …
> Remove quotes around env variable name in resolveBuildSecretEnv

- .github/workflows/codeql.yml
- src/buildx/builder.ts
[ESEC-20](https://docker.atlassian.net/browse/ESEC-20)
[ESEC-20]: https://docker.atlassian.net/browse/ESEC-20?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: enable SAST scanning with CodeQL

- .github/workflows/test.yml
- __tests__/docker/install.test.itg.ts
- src/docker/assets.ts
- src/docker/install.ts
related to https://github.com/crazy-max/ghaction-setup-docker/issues/45
colima only supports Ubuntu image since 0.6.0 which runs docker as systemd unit: https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#version-v060-and-newer
> ### Version v0.6.0 and newer
> 
> Colima uses Ubuntu as the underlying image. Other distros are not supported.
> docker(install): fallback to journalctl to print docker daemon logs

- __tests__/docker/install.test.itg.ts
- package.json
- src/docker/assets.ts
- src/docker/install.ts
- yarn.lock
related to https://github.com/docker/actions-toolkit/pull/201#issuecomment-1814246382
closes #210
closes #160
closes #157
> docker(install): switch to lima

- __tests__/docker/install.test.itg.ts
- __tests__/docker/install.test.ts
- src/docker/assets.ts
- src/docker/install.ts
- src/util.ts
related to https://github.com/crazy-max/ghaction-setup-docker/actions/runs/7158220214/job/19490045126?pr=48#step:3:146
```
/usr/local/bin/limactl start --name=docker-actions-toolkit --tty=false
time="2023-12-10T13:49:57Z" level=info msg="Using the existing instance \"docker-actions-toolkit\""
time="2023-12-10T13:49:57Z" level=info msg="QEMU binary \"/usr/local/bin/qemu-system-x86_64\" seems properly signed with the \"com.apple.security.hypervisor\" entitlement"
time="2023-12-10T13:49:57Z" level=info msg="Attempting to download the image" arch=x86_64 digest="sha256:054db2d88c454bb0ad8dfd8883955e3946b57d2b0bf0d023f3ade3c93cdd14e5" location="https://cloud-images.ubuntu.com/releases/22.04/release-20231026/ubuntu-22.04-server-cloudimg-amd64.img"
Downloading the image …
```
> docker(install): allow specifying custom lima images

- src/buildx/bake.ts
related to https://github.com/docker/bake-action/actions/runs/7274951418/job/19821919843#step:6:120
Currently when parsing definitions fails it would return an error but not on the correct line:
```
Error: #1 [internal] load local bake definitions
#1 reading ./test/config.hcl 623B / 623B done
#1 reading . 0B / 4.10kB done
#1 DONE 0.0s
ERROR: read .: is a directory
```
This change ensures we return the right line (here `read .: is a directory`) like we do in bake-action and build-push-action: https://github.com/docker/bake-action/blob/52a1696536aaa8818afd3753a71ec46298b8a19b/src/main.ts#L89
> bake: correctly match error when parsing definition

- __tests__/context.test.ts
- __tests__/github.test.ts
- src/buildx/inputs.ts
- src/github.ts
related to https://github.com/docker/build-push-action/pull/1049#issue-2116505864
replaces `Context.provenanceBuilderID` with new `GitHub.workflowRunURL` method.
> github: workflowRunURL

- .github/workflows/buildx-lab-releases-json.yml
- .github/workflows/buildx-releases-json.yml
- .github/workflows/docker-releases-json.yml
Missing bump of `actions/download-artifact`. Needs to bump `crazy-max/.github/.github/workflows/releases-json.yml` as well for artifact v4 support.
> bump actions/download-artifact to v4

- __tests__/buildx/install.test.ts
- src/buildx/install.ts
- src/cache.ts
related to https://github.com/docker/setup-buildx-action/issues/293
Adds `ghaNoCache` opt to `download` and `build` methods for buildx install. This is to allow users to opt-out caching in GitHub actions cache backend.
> buildx: ghaNoCache opt for download/build to disable binary cache

- __tests__/buildx/builder.test.ts
- __tests__/fixtures/inspect11.txt
- src/buildx/builder.ts
- src/types/builder.ts
follow-up https://github.com/docker/buildx/pull/2268, https://github.com/docker/buildx/pull/1854
related to https://github.com/docker/buildx/issues/2325#issuecomment-1985424880
Since Buildx 0.13, some keys have been renamed for `buildx inspect` command: https://github.com/docker/buildx/pull/2268/files#diff-201694404c6fd5e0d301670e34752d92835c43f21dc8e59e342b80a26848ec6fR87-R91
Also adds support for https://github.com/docker/buildx/pull/1854 available since Buildx 0.11.
> builder: update inspect command parsing

- __tests__/cache.test.itg.ts
- src/cache.ts
- src/index.ts
follow-up https://github.com/docker/actions-toolkit/pull/241
This moves github actions cache save handling in post step like it's currently done with official actions such as `actions/setup-go`.
> cache: move gha cache save to post state

- src/cache.ts
- src/index.ts
follow-up https://github.com/docker/setup-buildx-action/actions/runs/8299720155/job/22716669682#step:7:44
It's better to group cache logs to avoid it being mixed with other post steps.
> cache: run cache.post in core.group

- __tests__/buildx/inputs.test.ts
- __tests__/util.test.ts
- src/buildx/inputs.ts
- src/util.ts
follow-up https://github.com/docker/build-push-action/pull/1086#pullrequestreview-1960645719
> buildx: hasAttestationType and resolveAttestationAttrs funcs

- __tests__/buildx/bake.test.itg.ts
- __tests__/buildx/bake.test.ts
- src/buildx/bake.ts
- src/types/bake.ts
`provenance`, `sbom` and `no-cache` opts were missing when parsing the definition. `shm-size` and `ulimits` attributes have been added to `Target` struct as well related to https://github.com/docker/buildx/pull/2242
Also adds `execOptions` opt that will be used in bake-action to handle specific options accordingly. This is related to https://github.com/docker/bake-action/pull/193 where I was testing loading a remote bake definition from a private repo which doesn't give enough context when failing due to `silent: true`.
> bake: additional opts when parsing definition

- .github/workflows/test.yml
- __tests__/buildx/bake.test.itg.ts
- __tests__/fixtures/bake-test-docker-action-remote-private.json
- dev.Dockerfile
- src/buildx/bake.ts
- src/buildx/inputs.ts
We got the following output when trying to build from a remote bake definition on a private repo: https://github.com/docker/test-docker-action/tree/remote-private
```
$ docker buildx bake https://github.com/docker/test-docker-action.git#remote-private
#0 building with "default" instance using docker driver
#1 [internal] load git source https://github.com/docker/test-docker-action.git#remote-private
#1 0.225 fatal: could not read Username for 'https://github.com': terminal prompts disabled
#1 ERROR: failed to fetch remote https://github.com/docker/test-docker-action.git: git error: exit status 128
stderr:
fatal: could not read Username for 'https://github.com': terminal prompts disabled
------
> [internal] load git source https://github.com/docker/test-docker-action.git#remote-private: …
```
> bake: handle git auth token when parsing remote definition

- __tests__/docker/docker.test.itg.ts
- src/docker/docker.ts
fixes https://github.com/docker/setup-qemu-action/issues/122
closes https://github.com/docker/setup-qemu-action/pull/125
Adds `parseRepoTag` and `pull` to docker module. `pull` has been added to add cache support related to https://github.com/docker/setup-qemu-action/issues/110 and https://github.com/crazy-max/ghaction-xgo/issues/224
> docker: parseRepoTag and pull methods

- src/docker/docker.ts
introduced by second commit in https://github.com/docker/actions-toolkit/pull/200/commits/fc4dae47b637c9cec4371287c3e1798d262fa3dd#diff-d7be6b531f5d6821302968cc601218e4d174278b30cb452fca615843b1235f09R138
> docker: fix pull caching

- __tests__/util.test.ts
- src/util.ts
will be used for GHA summary to display build record bundle size.
> util: formatFileSize

- src/buildx/builder.ts
Similar to `buildx inspect` command, builder name can be omitted to return info of current builder.
> buildx: make name opt optional when inspecting builder

- .github/workflows/virtual-env.yml
related to https://github.blog/changelog/2024-05-14-github-hosted-runners-public-beta-of-ubuntu-24-04-is-now-available/
> ci(virtual-env): add ubuntu-24.04 to the matrix

- __tests__/buildx/history.test.itg.ts
- __tests__/github.test.itg.ts
- package.json
- src/buildx/history.ts
- src/github.ts
- src/types/github.ts
- src/types/history.ts
- yarn.lock
* ~needs https://github.com/docker/actions-toolkit/pull/307~
> github: write build summary

- __mocks__/@actions/github.ts
- __tests__/buildx/build.test.ts
- __tests__/github.test.ts
- jest.config.itg.ts
- jest.config.ts
- src/github.ts
We should set the number of attempts in the workflow run URL otherwise `builder-id` in provenance could be inaccurate.
> github: set attempts to workflowRunURL

- __tests__/buildx/build.test.ts
- __tests__/github.test.ts
- src/buildx/build.ts
- src/github.ts
follow-up https://github.com/moby/buildkit/pull/4788#pullrequestreview-1957611969
When using `gha` cache export type, set `repository` and `ghtoken` attributes.
Needs follow-up on `build-push-action` and `bake-action` to use this func.
> buildx(build): resolveCacheToAttrs func

- __tests__/util.test.ts
Add a single test to define behavior when an empty string is passed to the input list.
For context, my team was trying to determine a proper default value to set in a re-packaged internal version of docker/build-push-action@v4's `platform` field. We wanted to make this configurable, but wanted to provide a valid default value that wouldn't change behavior as we previously didn't set this. Checking the source, led us here where we didn't find it included in the test spec. Adding this test should make the expected behavior well defined and allow folks to depend on it.
> Add a test to define behavior when empty parameters are passed

- src/types/buildkit/buildkit.ts
- src/types/buildkit/client.ts
- src/types/buildkit/control.ts
- src/types/buildkit/ops.ts
- src/types/buildkit/rpc.ts
Adds BuildKit types that will be used in #302 (related to https://github.com/docker/buildx/pull/2511) and #347.
Atm these types are manually crafted based on generated proto from BuildKit repository:
* https://github.com/moby/buildkit/blob/v0.14.0/api/services/control/control.pb.go
* https://github.com/moby/buildkit/blob/v0.14.0/solver/pb/ops.pb.go
* https://github.com/moby/buildkit/blob/v0.14.0/vendor/github.com/gogo/googleapis/google/rpc/status.pb.go
* https://github.com/moby/buildkit/blob/v0.14.0/vendor/github.com/gogo/protobuf/types/any.pb.go
In follow-up we should generate these types with a tool like https://github.com/stephenh/ts-proto.
@nico1510 @austin5456 let me know if this is something that could be used on DD side by either using the actions-toolkit module: …
> buildkit: add types

- .github/workflows/test.yml
- __tests__/util.test.ts
- src/github.ts
- src/util.ts
fixes #367 
Use relative path for artifact link to avoid broken links.
Summary example from integration tests: https://github.com/docker/actions-toolkit/actions/runs/9554693648#summary-26336341867
Artifact link: https://github.com/docker/actions-toolkit/actions/runs/9554693648/artifacts/1610289579
Raw output: https://github.com/docker/actions-toolkit/actions/runs/9554693648/jobs/19145276140/summary_raw
```
<p>:arrow_down: <a href="./9554693648/artifacts/1610289579"><strong>docker~actions-toolkit~WZAZKH.dockerbuild</strong></a> (5.87 KB)<br>
```
___
Added extra commit to convert `.dockerbuild` filename and build name in the summary to unicode entities.
Has been tested on a private repo where a secret value is part of the `.dockerbuild` filename:
In this case `test-docker-action` is used as …
> github(summary): use relative path for artifact link and fix filename

- src/buildx/history.ts
fixes https://github.com/docker/build-push-action/issues/1143
closes https://github.com/docker/build-push-action/pull/1145
Build summary requires Buildx `dial-stdio` command available since Buildx 0.13.0. This adds an extra check to make sure current Buildx version is supported before exporting.
> buildx(history): check buildx version before exporting

- .github/workflows/buildx-lab-releases-json.yml
- .github/workflows/buildx-releases-json.yml
- .github/workflows/docker-releases-json.yml
releases json workflows should be triggered on PR only if the workflow file itself has changed.
> ci: only trigger releases json workflow on pr when changed

- __tests__/fixtures/hello-err.Dockerfile
- __tests__/github.test.itg.ts
- __tests__/util.test.ts
- src/github.ts
- src/util.ts
fixes #369 
Based on https://github.com/docker/actions-toolkit/actions/runs/9597296326?pr=377#summary-26466096422
Example here: https://github.com/docker/actions-toolkit/actions/runs/9599193396#summary-26472403316
cc @ruffsl @Pesa
> github(summary): add collapsible section for build inputs and bake def

- package.json
- src/github.ts
- yarn.lock
related to https://github.com/docker/actions-toolkit/actions/runs/9594377879/attempts/1#summary-26456810814
> github(summary): escape HTML when printing build error

- src/github.ts
relates to https://github.com/docker/build-push-action/issues/1154
[`@actions/artifact`](https://www.npmjs.com/package/@actions/artifact) v2+ is not yet supported on GHES. Users trying to upload an artifact will have an error that doesn't give enough context:
```
Failed to get backend IDs: The provided JWT token is invalid and/or missing claims
```
Before trying to downgrade to v1 we should at least return a better error message. This is similar to what `actions/upload-artifact` currently returns: https://github.com/actions/toolkit/blob/361a115e538ac6d8eb06cc47f3fcecce557d04c8/packages/artifact/src/internal/shared/errors.ts#L32
> github(artifact): check upload artifact support for GHES

- src/github.ts
updates learn more link to the docker blog post https://www.docker.com/blog/new-beta-feature-deep-dive-into-github-actions-docker-builds-with-docker-desktop/
> github(summary): update learn more link

- .github/workflows/test.yml
- __tests__/fixtures/lint.Dockerfile
- __tests__/github.test.itg.ts
- src/github.ts
* ~needs #362~
example in this PR through integration tests: https://github.com/docker/actions-toolkit/pull/365/files#diff-cc857d138abc3f09c4d212a933d59584a266fe71521fd2cd87327dc037558a43R17
___
___
> github: annotate build warnings

- __tests__/buildx/bake.test.ts
- src/buildx/bake.ts
- src/types/buildx/bake.ts
Use same type for build and bake
> bake: align build metadata

- src/buildx/bake.ts
we should return `undefined` if no ref has been found otherwise following cond https://github.com/docker/bake-action/blob/ff7b24e38552946f89b1398525bf9ec25e6de60e/src/main.ts#L212-L214 is always true and seeking refs in local state would never be done.
> buildx: fix resolveRefs for bake

- src/buildx/history.ts
fixes https://github.com/docker/build-push-action/issues/1156
> buildx(history): detach dial-stdio process

- __tests__/docker/docker.test.itg.ts
- __tests__/docker/docker.test.ts
- src/docker/docker.ts
- src/types/docker/docker.ts
relates to https://github.com/docker/setup-buildx-action/issues/311
> docker: contextInspect func

- __tests__/buildx/buildx.test.ts
- __tests__/fixtures/buildx-refs/default/default/7pnnqpgacnqq98oa1a1h5sz6t
- __tests__/fixtures/buildx-refs/default/default/84p2qpgacnqq98oa1a1h5sz6t
- __tests__/fixtures/buildx-refs/default/default/a5s9rlg9cnqq98oa1a1h5sz6t
- __tests__/fixtures/buildx-refs/default/default/aav2ix4nw5eky66fw045dkylr
- __tests__/fixtures/buildx-refs/default/default/w38vcd5fo5cfvfyig77qjec0v
- src/buildx/buildx.ts
relates to https://github.com/docker/actions-toolkit/pull/401#discussion_r1666694029
> buildx: fix broken local state

- __tests__/buildx/history.test.itg.ts
- src/buildx/history.ts
`DOCKER_BUILD_EXPORT_BUILD_IMAGE` can be used to set custom image for export-build tool. Will be used for testing purpose atm.
> buildx(history): env var to override export build image

- __tests__/docker/docker.test.itg.ts
- src/buildx/history.ts
- src/docker/docker.ts
relates to https://github.com/docker/build-push-action/issues/1185
> buildx(history): check docker daemon is running before exporting

- __tests__/.fixtures/lint.Dockerfile
- src/buildx/buildx.ts
relates to https://github.com/docker/build-push-action/issues/1204
> buildx: use Buffer for base64 encoding of the Dockerfile

- src/context.ts
fixes https://github.com/docker/build-push-action/issues/1222
When calling `ls-remote` for Git source in BuildKit like:
```
$ git ls-remote https://github.com/moby/buildkit
185751bdc010f1f8bf1192d6e9b4ec19552d5741        HEAD
05766c5c21a1e528eeb1c3522b2f05493fe9ac47        refs/heads/docker-18.09
396bfe20b590914cd77945ef0d70d976a0ed093c        refs/heads/docker-19.03
185751bdc010f1f8bf1192d6e9b4ec19552d5741        refs/heads/master
d52b2d58424260a86a0387472a59f9a48e522c10        refs/heads/v0.10
435cb77e369c618b9495617278cd276f75bbabe4        refs/heads/v0.11
dbed8c0a42162d1f3e9ec89038d95575e78f8759        refs/heads/v0.12
2e18d709fefdcc2db20853ee241c75b058189d39        refs/heads/v0.13
eb864a84592468ee9b434326cb7efd66f58555af        refs/heads/v0.14 …
```
> context: fix pull request ref

- __tests__/docker/install.test.itg.ts
- __tests__/docker/install.test.ts
- src/docker/assets.ts
- src/docker/install.ts
- src/dockerhub.ts
- src/hubRepository.ts
- src/types/docker/mediatype.ts
- related to: https://github.com/crazy-max/ghaction-setup-docker/issues/81
Add support for installing Docker `master` packages from `moby/moby-bin` and `dockereng/cli-bin` images.
This could also allow to install arbitrary version from these images but for now it's only used for `master`.
Test run: https://github.com/docker/moby-private/actions/runs/10773693004/job/29874033854?pr=9#step:2:336
> docker/install: Support `version: master`

- __tests__/docker/install.test.itg.ts
- src/docker/install.ts
Use the actual version number resolved from the Github releases instead of the `latest` string.
> docker/install: Fix lima failing to download latest Docker archive

- __tests__/docker/install.test.itg.ts
- src/docker/assets.ts
- src/docker/install.ts
- src/hubRepository.ts
- src/types/docker/mediatype.ts
- src/types/oci/mediatype.ts
`latest` is not a valid git tag or revision to get the matching systemd unit files.
Look up the exact source git commit from the `org.opencontainers.image.revision` image config label.
> docker/install: Fix latest image install on lima

- __tests__/docker/install.test.itg.ts
- src/docker/install.ts
Add support for running a rootless daemon. Currently only Linux host is supported.
> docker/install: Support rootless

- __tests__/docker/install.test.itg.ts
- src/docker/install.ts
Fix failure observed in: https://github.com/crazy-max/ghaction-setup-docker/pull/124
> docker/install: Fix rootless install, make teardown also cleanup the toolDir

- __tests__/git.test.ts
- src/git.ts
for https://github.com/docker/metadata-action/pull/308
sorry to create this PR again, I did some force push and it cause github not working as expected.
and looks like ci failed with other tests, not caused be this PR？
> feat: add method to get commit date from git

- src/docker/install.ts
relates to https://github.com/docker/actions-toolkit/actions/runs/11893136762/job/33137504565#step:11:1112
```
Error: Unable to locate executable file: qemu-system-x86_64. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
at Object.<anonymous> (/Users/runner/work/actions-toolkit/actions-toolkit/node_modules/@actions/io/src/io.ts:170:15)
at Generator.next (<anonymous>)
at fulfilled (/Users/runner/work/actions-toolkit/actions-toolkit/node_modules/@actions/io/lib/io.js:24:58)
```
> docker(install): check qemu is installed

- .github/workflows/test.yml
https://github.com/actions/runner-images/issues/10721
> ci: remove deprecated macos-12 runner

- .github/workflows/build.yml
- .github/workflows/test.yml
- docker-bake.hcl
GitHub runners support both node 18 and 20.
> ci: test supported node versions

- .github/workflows/buildx-lab-releases-json.yml
- .github/workflows/buildx-releases-json.yml
- .github/workflows/docker-releases-json.yml
- .github/workflows/undock-releases-json.yml
follow-up:
* https://github.com/crazy-max/.github/pull/25
* https://github.com/crazy-max/.github/pull/26
Handles `edge` releases so RCs can be tested without updating the tag, for example: https://github.com/docker/actions-toolkit/actions/runs/12049171417/job/33595366893#step:4:12
```json
{
"latest": {
"id": 176167883,
"tag_name": "v27.3.1",
"html_url": "https://github.com/moby/moby/releases/tag/v27.3.1",
"assets": []
},
"edge": {
"id": 186229632,
"tag_name": "v27.4.0-rc.2",
"html_url": "https://github.com/moby/moby/releases/tag/v27.4.0-rc.2",
"assets": []
},
"v27.4.0-rc.2": {
"id": 186229632,
"tag_name": "v27.4.0-rc.2",
"html_url": "https://github.com/moby/moby/releases/tag/v27.4.0-rc.2",
"assets": []
},
"v27.4.0-rc.1": {
"id": 185528936,
"tag_name": "v27.4.0-rc.1",
"html_url": …
```
> ci: update releases-json to 7f83a5a

- .github/workflows/buildx-releases-json.yml
This reverts commit 4ea16daf186c653e23246d9669d8f7d175e61107.
Buildx v0.19.1 has been released.
> Revert "ci: pin buildx latest to v0.18.0"

- .github/workflows/test.yml
- __tests__/docker/install.test.itg.ts
- src/docker/assets.ts
- src/docker/install.ts
This will be used in https://github.com/docker/setup-docker-action
> docker(install): opt to expose local tcp address

- __tests__/buildx/install.test.ts
- src/buildx/install.ts
Renames `lab` to `cloud` for buildx install version key.
The `lab` key was initially used to provide Buildx releases with features that could not yet fit with public consumption on the upstream repository, such as the `cloud` driver. As we do not expect any other features besides the `cloud` driver support, it is better to make this clear with this change. We keep backward compatibility if someone sets `lab`.
> buildx(install): rename lab to cloud

- __tests__/.fixtures/bake-01-overrides.json
- __tests__/.fixtures/bake-01-validate.json
- __tests__/.fixtures/bake-03-default.json
- __tests__/.fixtures/bake-03.hcl
- __tests__/.fixtures/bake-buildx-0.10.4-binaries-cross.json
- __tests__/buildx/bake.test.ts
- src/buildx/bake.ts
- src/types/buildx/bake.ts
fixes https://github.com/docker/actions-toolkit/issues/503
This adds support for composable attributes with backward compatibility for csv syntax.
> bake: support composable attributes

- __tests__/context.test.ts
- src/context.ts
related to
* https://github.com/docker/actions-toolkit/pull/457
* https://github.com/docker/build-push-action/issues/1222
Using the `/head` ref for pull requests by default is problematic, as it fails to capture upstream changes in the target branch. This discrepancy might lead to different outcomes in CI runs compared to those obtained when running the same workflows against the target branch after merging a PR.
With this change, users will need to set the `DOCKER_DEFAULT_GIT_CONTEXT_PR_HEAD_REF=true` environment variable in their workflows to opt in to tracking the `HEAD` of the development branch, rather than the merge branch that previews the changes after merging into the target branch.
cc @chandanpg
> context: opt-in pull request head ref

- src/context.ts
This function is not used anymore and has been replaced by https://github.com/docker/actions-toolkit/blob/9881e80bfd28a1eab4cbc17ecffbb8fc7318d41b/src/github.ts#L93-L95
Used when solving provenance attributes: https://github.com/docker/actions-toolkit/blob/9881e80bfd28a1eab4cbc17ecffbb8fc7318d41b/src/buildx/build.ts#L162
> context: remove provenanceBuilderID func

- __tests__/github.test.itg.ts
relates to https://github.com/docker/actions-toolkit/actions/runs/12843876100/job/35816318775#step:10:809
```
ERROR: read unix @->/run/docker.sock: use of closed network connection
FAIL __tests__/github.test.itg.ts (50.913 s)
● uploadArtifact › uploads an artifact
Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
at ArtifactHttpClient.<anonymous> (node_modules/@actions/artifact/src/internal/shared/artifact-twirp-client.ts:69:13)
at Generator.throw (<anonymous>)
at rejected (node_modules/@actions/artifact/lib/internal/shared/artifact-twirp-client.js:6:65)
```
> test(github): generate random filename

- .github/workflows/test.yml
- .github/workflows/virtual-env.yml
- __tests__/docker/install.test.ts
* https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
* https://github.com/actions/partner-runner-images
> ci: add ubuntu arm runners

- __tests__/.fixtures/inspect11.txt
- __tests__/buildx/builder.test.ts
- src/buildx/builder.ts
- src/types/buildx/builder.ts
follow-up https://github.com/docker/buildx/pull/2684
> builder: support files in inspect command

- src/compose/install.ts
Atm it would install under `/home/runner/.bin/<version>/<platform>/docker-compose` like `/home/runner/.bin/2.32.4/linux-x64/docker-compose`
We should put the binary under a common folder to avoid confusion.
> compose(install): fix base cache dir

- src/buildx/build.ts
This PR removes the explicit `encoding: 'utf-8'` from the secret resolution code to ensure binary files are not corrupted. Previously, reading and writing secrets as UTF-8 caused issues when the secret was a binary file. By switching to raw buffers, the code now correctly supports both binary and text-based secrets without any unintended transformations.
- **Removed** `encoding: 'utf-8'` from `fs.readFileSync`.
- **Ensured** raw buffers are used when reading and writing secrets, preventing data corruption.
- **Maintains** existing behavior for text-based secrets, while adding proper support for binary data.
> Fix: Remove UTF-8 encoding to prevent mangling of binary secrets

- src/docker/assets.ts
Update to latest stable and set kernel and initrd opts for aarch64 image to fix possible kernel panic on boot related to https://github.com/docker/setup-docker-action/issues/136
cc @AkihiroSuda
> docker(install): update lima images

- .github/workflows/regclient-releases-json.yml
relates to https://github.com/docker/actions-toolkit/pull/567#issuecomment-2601081156
We can use [regclient](https://github.com/regclient/regclient) to get the image config. This tool could also be useful for other cases with our actions.
> ci: regclient releases json workflow

- __tests__/undock/undock.test.itg.ts
relates to https://github.com/docker/actions-toolkit/actions/runs/14594348825/job/40936688791?pr=674#step:10:56
```
FAIL __tests__/undock/undock.test.itg.ts (13.326 s)
● run › extracts moby/moby-bin:26.1.5
expect(received).resolves.not.toThrow()
Received promise rejected instead of resolved
Rejected to value: [Error: The process 'C:\Users\RUNNER~1\AppData\Local\Temp\docker-actions-toolkit-o3gf3u\runner-temp\docker-actions-toolkit-F6FfTn\undock-bin\undock.exe' failed with exit code 1]
38 |
39 |     const undock = new Undock();
> 40 |     await expect(
|                 ^
41 |       (async () => {
42 |         // prettier-ignore
43 |         await undock.run({
at expect (node_modules/expect/build/index.js:113:15)
at __tests__/undock/undock.test.itg.ts:40:17
at fulfilled …
```
> undock: fix integration test

- __tests__/buildx/install.test.ts
- __tests__/compose/install.test.ts
- __tests__/regclient/install.test.ts
- __tests__/undock/install.test.ts
relates to https://github.com/docker/actions-toolkit/actions/runs/14441399670/job/40492173583#step:2:3047
```
#25 111.9 FAIL __tests__/undock/install.test.ts (33.919 s)
#25 111.9   ● download › acquires "v0.5.0" of undock without cache
#25 111.9 
#25 111.9     thrown: "Exceeded timeout of 5000 ms for a test.
#25 111.9     Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."
#25 111.9 
#25 111.9       63 |     ['v0.5.0'],
#25 111.9       64 |     ['v0.6.0'],
#25 111.9     > 65 |   ])(
#25 111.9          |     ^
#25 111.9       66 |   'acquires %p of undock without cache', async (version) => {
#25 111.9       67 |     const install = new Install();
#25 111.9       68 |     const toolPath = await …
```
> test: set proper timeout when downloading binaries

- jest.config.itg.ts
No need specific envs when running integration tests suite like we do with sandbox mode.
> fix jest config for integration tests

- src/buildx/history.ts
- src/github.ts
- src/types/buildx/history.ts
- src/types/github.ts
follow-up https://github.com/docker/build-push-action/pull/1370#discussion_r2084316954
alternative and closes #685
For single build:
When there are multiple refs built (with bake-action), the build URL will be set within the summary table for each record.
> github: support cloud build URL when writing summary

- src/github.ts
Turns out cloud driver endpoint has a `cloud://` protocol set that we need to take into account. Also fixes an issue where cloud build URL intro was incorrectly displayed for multiple build refs.
> github: fix summary handling for dbc

- .github/workflows/build.yml
- .github/workflows/test.yml
Node 24 support is available since runner version 2.327.1 https://github.com/actions/runner/releases/tag/v2.327.1
Didn't default yet to Node 24, I prefer to await at least a month until enough people on self-hosted runners and GHES are compatible.
> ci: test node 24
